// Contains all docker-compose configuration parameters
export default {
  build: {
    type: 'string',
    settings: ['context', 'dockerfile', 'args', 'cache_from', 'labels'],
  },
  command: ['string', 'array'],
  configs: 'array',
  labels: 'object',
  cap_add: 'array',
  cap_drop: 'array',
  context: 'string',
  type: 'string',
  dockerfile: 'string',
  args: 'object',
  cache_from: 'array',
  cgroup_parent: 'string',
  credential_spec: {
    type: 'string',
    settings: ['file', 'registry'],
  },
  devices: 'array',
  depends_on: 'array',
  dns: ['string', 'array'],
  dns_search: ['string', 'array'],
  tmpfs: ['string', 'array'],
  entrypoint: ['string', 'array'],
  env_file: ['string', 'array'],
  environment: ['array', 'object'],
  expose: ['array'],
  external_links: ['array'],
  extra_hosts: ['array'],
  healthcheck: {
    type: 'object',
    settings: ['test', 'interval', 'timeout', 'retries'],
  },
  isolation: 'string',
  links: 'array',
  logging: 'object',
  network_mode: 'string',
  networks: {
    type: ['array', 'object'],
    settings: ['aliases'],
  },
  aliases: {
    type: ['array', 'object'],
    settings: ['ipv4_address', 'ipv6_address', 'ipam', 'enable_ipv6', 'driver'],
  },
  pid: 'string',
  ports: {
    type: ['array', 'object'],
    settings: ['target', 'published', 'protocol', 'mode'],
  },
  secrets: ['array', 'object'],
  stop_grace_period: 'string',
  stop_signal: 'string',
  sysctls: 'string',
  ulimits: 'object',
  userns_mode: 'string',
  volumes: {
    type: ['array', 'object'],
    settings: ['type', 'source', 'target', 'volume'],
  },
  user: 'string',
  working_dir: 'string',
  domainname: 'string',
  hostname: 'string',
  ipc: 'string',
  mac_address: 'string',
  privileged: 'boolean',
  read_only: 'boolean',
  shm_size: 'string',
  stdin_open: 'boolean',
  tty: 'boolean',
  restart: 'string',
  deploy: { // version 3
    type: 'object',
    settings: [
      'replicas',
      'update_config',
      'restart_policy',
      'labels',
      'mode',
      'placement',
      'resources',
      'endpoint_mode', // version 3.3
    ],
    not_supported: [
      'build',
      'cgroup_parent',
      'container_name',
      'devices',
      'dns',
      'dns_search',
      'tmpfs',
      'external_links',
      'links',
      'network_mode',
      'security_opt',
      'stop_signal',
      'sysctls',
      'userns_mode',
    ],
  },
};
